server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'sartech'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    show-sql: 'true'
